steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy to GKE cluster
    args:
      - '-c'
      - |
        helm init --client-only
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=knowhub'
      - 'CLOUDSDK_CORE_PROJECT=endless-tractor-248005'