steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy to GKE cluster
    args: ['get', 'pod', '-n', 'knowhub']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=knowhub'
      - 'CLOUDSDK_CORE_PROJECT=endless-tractor-248005'