steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: test
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo 'this is a test trigger'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=knowhub-test'
      - 'CLOUDSDK_CORE_PROJECT=knowhub-new'