steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy to GKE cluster
    entrypoint: bash
    args:
      - '-c'
      - |
        bash /builder/kubectl.bash version && \
        kubectl get po -n knowhub && \
        snap install helm --classic
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=knowhub'
      - 'CLOUDSDK_CORE_PROJECT=endless-tractor-248005'