# Example configuration file: always override with a specific cluster configuration file!

projectId: "knowhub-new"
domain: 'knowhub-test.com'
acmeRegistrationEmail: 'luca.poddigue@knowhub.it'

certCommonName: "*.{{ .Values.domain }}"
certDnsNames: |
  - "*.{{ .Values.domain }}"