apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: demo-certificate
spec:
    acme:
        config:
            - dns01:
                  provider: cloud-dns-provider
              domains:
                  - '*.knowhub-gateway.com'
    commonName: '*.knowhub-gateway.com'
    dnsNames:
        - '*.knowhub-gateway.com'
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-issuer
    secretName: istio-customingressgateway-certs