apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: demo-certificate
spec:
    acme:
        config:
            - dns01:
                  provider: cloud-dns-provider
              domains:
                  - {{ include "knowhub.dnsName"}}
    commonName: {{ include "knowhub.dnsName"}}
    dnsNames:
        - {{ include "knowhub.dnsName"}}
    issuerRef:
        kind: ClusterIssuer
        name: letsencrypt-issuer
    secretName: istio-customingressgateway-certs