apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
    name: {{ include "knowhub.cert-issuer-name" . }}
spec:
    acme:
        # The ACME server URL
        server: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: luca.poddigue@knowhub.it
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: {{ include "knowhub.certIssuerName" . }}
        dns01:
            # Here we define a list of DNS-01 providers that can solve DNS challenges
            providers:
                - name: cloud-dns-provider
                  clouddns:
                      # The ID of the GCP project
                      project: {{ .Values.global.projectId }}
                      # This is the secret used to access the service account
                      serviceAccountSecretRef:
                          name: clouddns-dns01-solver-svc-acct
                          key: key.json