apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: "{{.Release.Name}}-istio-gateway"
    labels:
        {{- include "knowhub.labels" . | nindent 8 }}
spec:
    selector:
        istio: ingressgateway
    servers:
        - hosts:
                {{- tpl .Values.global.hosts $ | nindent 16 }}
          port:
              name: http
              number: 80
              protocol: HTTP
          tls:
              httpsRedirect: true
        - hosts:
                {{- tpl .Values.global.hosts $ | nindent 16 }}
          port:
              name: https
              number: 443
              protocol: HTTPS
          tls:
              mode: SIMPLE
              privateKey: /etc/istio/ingressgateway-certs/tls.key
              serverCertificate: /etc/istio/ingressgateway-certs/tls.crt