apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: {{ include "knowhub-cert-issuer.certificateName" . }}
    namespace: istio-system
    labels:
        {{- include "knowhub-cert-issuer.labels" . | nindent 8 }}
spec:
    commonName: "*.{{ .Values.global.domain }}"
    dnsNames:
        - "{{ .Values.global.domain }}"
        - "*.{{ .Values.global.domain }}"
    issuerRef:
        kind: ClusterIssuer
        name: {{ include "knowhub-cert-issuer.certIssuerName" . }}
    secretName: istio-ingressgateway-certs