apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: {{ include "knowhub-ingress-gateway.certificateName" . }}
    namespace: istio-system
    labels:
        {{- include "knowhub-ingress-gateway.labels" . | nindent 8 }}
spec:
    commonName: "{{ include "knowhub-ingress-gateway.domain" . }}"
    dnsNames:
        - "{{ include "knowhub-ingress-gateway.domain" . }}"
    issuerRef:
        kind: ClusterIssuer
        name: {{ include "knowhub-ingress-gateway.certIssuerName" . }}
    secretName: istio-ingressgateway-certs