apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: {{ include "frontend.name" . }}
    labels:
        {{- include "frontend.labels" . | nindent 8 }}
    annotations:
        "helm.sh/hook": "pre-install"
spec:
    cdn:
        enabled: true
        cachePolicy:
            includeHost: true
            includeProtocol: true
            includeQueryString: false