apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "frontend.name" . }}
    labels:
        {{- include "frontend.labels" . | nindent 8 }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
        {{- include "frontend.matchLabels" . | nindent 12 }}
    template:
        metadata:
            labels:
            {{- include "frontend.matchLabels" . | nindent 16 }}
        spec:
            volumes:
                - name: cache
                  emptyDir: {}
                - name: run
                  emptyDir: {}
                - name: temp
                  emptyDir: {}
            containers:
                - name: {{ .Chart.Name }}
                  image: "eu.gcr.io/knowhub-new/knowhub-frontend:{{ .Values.imageTag }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: {{ .Values.service.containerPort }}
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: {{ .Values.service.containerPort }}
                      initialDelaySeconds: 30
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: {{ .Values.service.containerPort }}
                        {{- with .Values.resources }}
                  resources:
            {{- toYaml .Values.resources | nindent 24 }}
        {{- end }}