apiVersion: v1
kind: Service
metadata:
    name: {{ include "frontend.name" . }}
    labels:
        {{- include "frontend.labels" . | nindent 8 }}
    annotations:
        beta.cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"{{ include "frontend.name" . }}"}}'
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.containerPort }}
          protocol: TCP
          name: http
    selector:
        {{- include "frontend.matchLabels" . | nindent 8 }}
