apiVersion: v1
kind: Service
metadata:
    name: {{ include "getting-started.fullname" . }}
    labels:
        {{ include "getting-started.labels" . | indent 4 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.httpPort }}
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "getting-started.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
