substitutions:
  _HELM_VERSION: 2.14.3
  _ENV: test
steps:
  - id: 'Decrypt Helm SSH keys'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud kms decrypt --ciphertext-file=.helm/ca.pem.enc --plaintext-file=.helm/ca.pem --location=global --keyring=build --key=helm-ssh && \
        gcloud kms decrypt --ciphertext-file=.helm/cert.pem.enc --plaintext-file=.helm/cert.pem --location=global --keyring=build --key=helm-ssh && \
        gcloud kms decrypt --ciphertext-file=.helm/key.pem.enc --plaintext-file=.helm/key.pem --location=global --keyring=build --key=helm-ssh
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy to GKE cluster
    entrypoint: bash
    args:
      - '-c'
      - |
        bash /builder/kubectl.bash version && \
        curl -4 -L https://get.helm.sh/helm-v${_HELM_VERSION}-linux-amd64.tar.gz -o /builder/helm.tar.gz && \
        tar -zxvf /builder/helm.tar.gz -C /builder && \
        mv /builder/linux-amd64/helm /usr/local/bin/helm
        helm init --client-only && \
        cd knowhub && \
        helm lint . && \
        helm lint charts/* -f values.yaml && \
        helm upgrade knowhub-$(_ENV) . --install --namespace knowhub-$(_ENV) -f envConfiguration/$(_ENV).yaml --debug --dry-run --tls --tls-ca-cert ../.helm/ca.pem --tls-cert ../.helm/cert.pem --tls-key ../.helm/key.pem > log.out
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=knowhub'
      - 'CLOUDSDK_CORE_PROJECT=endless-tractor-248005'