apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "knowhub.name" . }}
    labels:
        {{- include "knowhub.labels" . | nindent 8 }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            {{- include "knowhub.matchLabels" . | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "knowhub.matchLabels" . | nindent 16 }}
        spec:
            volumes:
                - name: secret-nginx
                  secret:
                      secretName: {{ include "knowhub.name" . }}-nginx
            containers:
                - name: {{ .Chart.Name }}
                  image: "eu.gcr.io/knowhub-new/quarkus-tutorial:{{ .Values.imageTag }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - name: backend
                        containerPort: {{ .Values.service.backendPort }}
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: backend
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: backend
                        {{- with .Values.resources }}
                  resources:
                        {{- toYaml .Values.resources | nindent 24 }}
                    {{- end }}
                - name: esp
                  image: gcr.io/endpoints-release/endpoints-runtime:1
                  args: [
                      "--ssl_port", "{{ .Values.service.port}}",
                      "--backend", "127.0.0.1:{{ .Values.service.backendPort}}",
                      "--service", "app.endpoints.{{ .Values.global.projectId}}.cloud.goog",
                      "--rollout_strategy", "managed"
                  ]
                  ports:
                      - containerPort: {{ .Values.service.port}}
                  volumeMounts:
                      - mountPath: /etc/nginx/ssl
                        name: secret-nginx
                        readOnly: true