apiVersion: v1
kind: Service
metadata:
    name: {{ include "backend.name" . }}
    labels:
        {{- include "backend.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
          name: https
          nodePort: null
    selector:
        {{- include "backend.matchLabels" . | nindent 8 }}
